### ISSUE TITLE
Using CentOS 7 image

### ISSUE THREAD

**Issue by mdevlin1** [chrismeyersfsu/provision_docker#12]
Hello, I am trying to use this ansible role with your CentOS 7 docker image, chrismeyers/centos7, and I am receiving some errors. It seems that sshing into the container is not working. I have tried the same configuration on your CentOS 6 image, chrismeyers/centos6, and it works properly. The errors I am getting are:

`TASK [provision_docker : Make sure ssh is really up] ***************************
failed: [localhost] (item={u'image': u'chrismeyers/centos7', u'name': u'test1'}) => {"item": {"image": "chrismeyers/centos7", "name": "test1"}, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
failed: [localhost] (item={u'image': u'chrismeyers/centos7', u'name': u'test2'}) => {"item": {"image": "chrismeyers/centos7", "name": "test2"}, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
`

**Comment by chrismeyersfsu** [comment]
What virtualization are you using? i.e. docker for mac, docker toolbox (virtualbox), fusion ?

**Comment by mdevlin1** [comment]
docker-engine on ubuntu 14.04

**Comment by chrismeyersfsu** [comment]
Ok, see if you can ssh manually to the docker instance. `docker ps` <-- find the instance in the list then run `docker inspect --format='{{.NetworkSettings.IPAddress}}' <docker_image_name_here>` to get the ip. Then see if you have a route to the image. `ping <ip_here>`. Now try ssh `ssh root@<ip_here>` password is `docker.io`.

**Comment by mdevlin1** [comment]
Ping works and I can manually ssh into the container

**Comment by mdevlin1** [comment]
Ok I have narrowed down the problem. I moved my ansible playbook to a different directory because I suspected my ansible.cfg file was the issue and it worked. I'm going to close this issue. Thank you for the help.
