### ISSUE TITLE
Cannot ping container

### ISSUE THREAD

**Issue by rfleschenberg** [chrismeyersfsu/provision_docker#13]
Hi, 

Trying to follow https://www.ansible.com/blog/testing-ansible-roles-with-docker, I run into this issue:

```
TASK [provision_docker : Make sure ssh is really up] ***************************
task path: /home/rene/.ansible/roles/provision_docker/tasks/inc_cloud_iface.yml:50
<172.17.0.3> ESTABLISH SSH CONNECTION FOR USER: root
<172.17.0.3> SSH: EXEC sshpass -d13 ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o User=root -o ConnectTimeout=10 -o ControlPath=/home/rene/.ansible/cp/ansible-ssh-%h-%p-%r 172.17.0.3 '/bin/sh -c '"'"'LANG=de_DE.UTF-8 LC_ALL=de_DE.UTF-8 LC_MESSAGES=de_DE.UTF-8 /usr/bin/python && sleep 0'"'"''
fatal: [localhost]: FAILED! => {"failed": true, "msg": "Using a SSH password instead of a key is not possible because Host Key checking is enabled and sshpass does not support this.  Please add this host's fingerprint to your known_hosts file to manage this host."}
```

Should we disable SSH host key checking? Or maybe it would be better to just include an SSH key for the purpose of running the tests and bake it into the containers?

**Comment by rfleschenberg** [comment]
I just noticed the `ansible.cfg` file. I wasn't running the playbook from the `test` directory, I guess this was the problem. Should maybe just add a note somewhere?

**Comment by chrismeyersfsu** [comment]
Yes. The underlying "issue" is that docker containers commonly get the same IP address. Thus the need for the ansible.cfg entries. Should we just note this in the README ?

**Comment by rfleschenberg** [comment]
I think documentation is the way to go here. How people want to deal with this will vary from case to case, so, making an explicit note and mentioning a possible solution seems like a good idea. For example, I like to use environment variables for such things (`ANSIBLE_HOST_KEY_CHECKING=False`). Most CI systems provide a way to set environment variables, so this should work in almost all cases.

I can send a PR if you allow me some time for it.

**Comment by chrismeyersfsu** [comment]
Please do !

**Comment by chrismeyersfsu** [comment]
ping

**Comment by rfleschenberg** [comment]
Sorry, I have been kind of busy. I still have this in my inbox. I hope to get around to it soon. Feel free to close the issue if you want, I will still send the PR eventually.
