### ISSUE TITLE
Crashes my Xserver

### ISSUE THREAD

**Issue by micarlise** [chrismeyersfsu/provision_docker#14]
I probably just don't have my environment configured correctly, but when I run the ansible-playbook, which is identical to the example that is on the blog post.  It starts running, brings up a docker host, and when it gets to the   'Wait for ssh' task, my Xserver appears to crash.  I'm not really sure exactly, but I lose my X Desktop, and then promptly brought back to my Display manager login window.

After logging in, I can see that a docker image is running wtih docker ps, but I can't attach to it.  

I have attached an ansible.log file of the playbook running.

[ansible.txt](https://github.com/chrismeyersfsu/provision_docker/files/450043/ansible.txt)

Any ideas where I should start looking?  I did outside of ansible, execute a docker run on the chrismeyers/centos6 image and it starts and I can attach to it.  I also can docker inspect the image, and ping the given IP address.

**Comment by chrismeyersfsu** [comment]
Are you using native docker, running docker in a VM, or docker for Mac? This seems to point not being able to access the network that the containers are running on. Check the README if your using virtual box or VMware fusion.

**Comment by micarlise** [comment]
@chrismeyersfsu 

That probably was the start of the issue.  I didn't check on it fora few days, so my machine has been restarted (and thus the docker service file).  I'm using native docker on Arch linux.  It's possible that my network did not have the docker IP addresses routable.

The example on the blog still does not work (HostKey Checking issues).  But I can play around with it from here.

I still can't understand why if the ssh timed out, my display manager would blank.  But I'm also not terribly concerned with it.

Thanks.

**Comment by evalexpr** [comment]
I'm aware this is super old, but we've recently started using this and I've had the exact same issue as above, also running Arch Linux

**Comment by micarlise** [comment]
@W1lkins b/c of the age of this issue; I can't be completely sure of how I got around this issue.  But if my memory serves me correctly, it had to do with running ansible as root.  Which I was doing b/c I didn't have my username part of the docker gid.  

Not sure if you are running as root, but if you are; I would suggest trying it on a non-root username and see if that fixes the issue.
