### ISSUE TITLE
Use `docker exec` rather than rely on SSH?

### ISSUE THREAD

**Issue by MidnightLightning** [chrismeyersfsu/provision_docker#15]
Seeing in the readme "`provision_docker` relies on being able to ssh to containers" and the klunky workaround for Macs running Docker made me wonder why `provision_docker` cannot use the `docker exec` command instead? That way it would only need the IP of the Docker host and not the IP of the individual containers to target a command on them?

**Comment by chrismeyersfsu** [comment]
Last I looked (and this may have changed), the docker connection plugin didn't support `sudo` and `su`. Does it now?

**Comment by chrismeyersfsu** [comment]
@MidnightLightning Looks like @turkenh has added support for what you want. PR #16 created, feedback welcome.
