### ISSUE TITLE
Allow assigning port mappings on docker containers

### ISSUE THREAD

**Issue by pavlosgi** [chrismeyersfsu/provision_docker#31]

**Comment by jos4uke** [comment]
hi
I tried to use ports/published_ports but no mappings occurred.
This would be very useful.
Thanks in advance

**Comment by lukas-bednar** [comment]
I am trying to do something about it here #51 but I am failing on test, the installation of apache gets stuck ...
I will try to move with it by end of the week.

**Comment by ghost** [comment]
Exactly what I need
