### ISSUE TITLE
Does this role work with docker-machine?

### ISSUE THREAD

**Issue by rrpolanco** [chrismeyersfsu/provision_docker#7]
I'm running docker-machine on Mac OS X (El Capitan) and I'm seeing the following error when running my playbook:

```
TASK [chrismeyersfsu.provision_docker : Wait for ssh] **************************
failed: [localhost] => (item={u'image': u'ubuntu-upstart:14.04', u'name': u'statsd_host_1'}) => {"elapsed": 30, "failed": true, "item": {"image": "ubuntu-upstart:14.04", "name": "statsd_host_1"}, "msg": "Timeout when waiting for 172.17.0.2:22"}
```

**Comment by chrismeyersfsu** [comment]
The method of relying on the docker IP does work with docker machine on Mac, but some tweaks required to the VM. You need to be able to access the network that the docker images are brought up in. I followed the tutorial below. Let me know if you need and further help, or if you get it working!

https://bobmaerten.eu/blog/passage-de-boot2docker-a-docker-machine/
